# Generated by Django 3.1.3 on 2020-12-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('job_detail', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('update_time', models.TextField(blank=True, null=True)),
                ('create_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
    ]
